import time
import sys

time.sleep(2)
print("Before we begin...")
time.sleep(1)
print("These questions are Case Sensitie!")
time.sleep(1)
print("Please try and use Capitals Appropriately!")
time.sleep(1)
print("This chat is protected with a Copyright License!")
time.sleep(1)
print(sys.copyright) 
name = input("What is your name? ")
time.sleep(1)
print("Hello " + name + "!")
time.sleep(1)
print("I am Chat!")
time.sleep(1)
print("An Automated Robot for the... ")
time.sleep(1)
print("Character")
time.sleep(1)
print("Helping")
time.sleep(1)
print("Assistant")
time.sleep(1)
print("Team")
time.sleep(1)
print("We have a form for you to answer")
time.sleep(1)
print("This form will be taking your data for company purposes")
time.sleep(1)
perms = input("Do you give concent to continue? ")
if perms == "Yes":
    time.sleep(1)
    print("Great!")
    time.sleep(1)
    import chat.chat_2 as chat_2
elif perms == "No":
    time.sleep(1)
    print("You will not be able to continue this form!")
    time.sleep(1)
    print("Goodbye!")
    sys.exit()
else:
    time.sleep(1)
    print("That is an invalid answer!")
    time.sleep(1)
    print("This form will now end for you")
    time.sleep(1)
    print("Goodbye!")
    sys.exit()